name = "share-chat"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

# Set via `wrangler secret put`:
# TURNSTILE_SITE_KEY
# TURNSTILE_SECRET_KEY

[[kv_namespaces]]
binding = "ROOMS"
id = "30e0db67037747d5aff5c1a431e97e04"

[[r2_buckets]]
binding = "FILES"
bucket_name = "share-chat-files"
